name: etax
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
  provider: ^6.0.2
  geolocator: ^8.2.0
  local_auth: ^1.1.11
  image_picker: ^0.8.5
  image_compare: ^1.1.2
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  khalti_flutter: ^2.0.2
  flutter_native_splash: ^2.1.6
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_native_splash:
  image: assets/app_logo.png
  color: "#042a49"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
